### ISSUE TITLE
Unresolved Dependencies

### ISSUE THREAD

**Issue by tfKamran** [goodbomb/angular-gulp-browserify-starter#26]
On downloading the package, when you do:

    npm install

and

    bower install

Still running `gulp build` throws an exception:

    module.js:338
        throw err;
              ^
    Error: Cannot find module 'parseurl'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (C:\Users\kamran.ansari\Downloads\angular-gulp-browserify-starter-master\angular-gulp-browserify-starter-master\node_modules\gulp-connect\node_modules\connect\lib\proto.js:13:16)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)

**Comment by goodbomb** [comment]
I just did a fresh install and it worked fine for me. I suspect it's an issue with your version of node. Which version are you running? You may need to update it. I'm running io.js v3.1.0 currently, but it was working before on the latest version of node.js v0.12.7
